name: 01 - Building Blocks

on: workflow_dispatch
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, wolrd"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Successful step
              run: |
                echo "I Succeed"
                exit 0
            - name: Say good bye
              run: echo "Good Bye"             
