name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{inputs.debug}}

on: 
  push:
  workflow_dispatch:
   inputs:
    debug:
      description: "Enable debug mode"
      required: false
      default: "false"

jobs: 
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_ENV: "This is from env block"
    steps:
      - name: Display contexts information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Custom Env: ${{ env.MY_ENV }}"

      - name: Retrieve Variable information
        run: |
          echo "Variable value from repo/org vars: ${{ vars.MY_VAR }}"

      - name: Debug Only Step
        if: ${{ inputs.debug == 'true' }}
        run: echo "Running in DEBUG mode!"
